<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>spotify-user-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SpotifyAPI.Web" />
    <PackageReference Include="SpotifyAPI.Web.Auth" />
    <ProjectReference Include="..\Alify.Core\Alify.Core.csproj" />
    <ProjectReference Include="..\Alify.ServiceDefaults\Alify.ServiceDefaults.csproj" />
    <PackageReference Include="TickerQ" />
    <PackageReference Include="TickerQ.Dashboard" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
