<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="HtmlAgilityPack" Version="1.11.62" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.44.0" />
    <PackageVersion Include="Serilog" Version="4.0.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageVersion Include="SpotifyAPI.Web" Version="7.1.1" />
    <PackageVersion Include="SpotifyAPI.Web.Auth" Version="7.1.1" />
    <PackageVersion Include="TickerQ" Version="2.3.0" />
    <PackageVersion Include="TickerQ.Dashboard" Version="2.3.0" />
  </ItemGroup>
</Project>