<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.54.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="SpotifyAPI.Web" Version="7.2.1" />
    <PackageVersion Include="SpotifyAPI.Web.Auth" Version="7.2.1" />
    <PackageVersion Include="TickerQ" Version="2.3.0" />
    <PackageVersion Include="TickerQ.Dashboard" Version="2.3.0" />
  </ItemGroup>
</Project>