<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>lyrics-user-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mscc.GenerativeAI" />
    <ProjectReference Include="..\Alify.Core\Alify.Core.csproj" />
    <ProjectReference Include="..\Alify.ServiceDefaults\Alify.ServiceDefaults.csproj" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
